### PR TITLE
Chore/mobile popup

### PR DESCRIPTION
**Pull request by JohanHjelsethStorstad**
This PR makes the PopUp better on mobile.
- The popup is now on the bottom of the screen on mobile
- The createOmbul popup is styled for mobile
- The system for choosing image for a cmsImage is now styled for mobile (it is a popup)

### CODE REVIEW

**Comment by theodorklauritzen** [comment]
On landscape on mobile the close button is not visible. And if the pop up has a lot of content maybe a `overflow-y: auto` is smart, to enable scroll.

**Comment by JohanHjelsethStorstad** [comment]
> On landscape on mobile the close button is not visible. And if the pop up has a lot of content maybe a `overflow-y: auto` is smart, to enable scroll.

I could not reproduce the problem with the close button. But what I can do is set max-height: 90svh on the popup content

**Comment by JohanHjelsethStorstad** [comment]
I guess you mean overflow: scroll

**Review by theodorklauritzen — APPROVED** [review]
I made a small change, but It's fine now :)))

**Comment by JohanHjelsethStorstad** [comment]
@Paulijuz  can you approve this?

**Review by Paulijuz — APPROVED** [review]
Looks good!

**Pull request merged**
