### PR TITLE
Feat/companies and contactor

### PR DESCRIPTION
**Pull request by JohanHjelsethStorstad**
WARNING merge after #346 as this branch includes those commits.
This PR adds a company system to PN, and uses them in the jobads system. It also does a general refactor:
- Jobads system moved to /career together with companies.
- The career landing page (added) links to companies and jobads as well as company-presentations (bedbress)
- To do this link to company-presentations on events safely a special-event-tag system has been added.
- The /career landing page somewhat adjusts based on if the user is logged in (Karriere) and not (For bedrifter)
- Includes a special CmsLink (new thing) that can be set to point to contactor.no. This special CmsLink will soon be useful on front-page and in nav-bar.
- Makes the Date component from #346 better by clearly stating that we are talking about UTC on initial render
- Changes the expiration date atr. on api-keys to also follow UTC convention in database and backend
- Modifies the <DateInput /> component so it displays local date to user while sending UTC to the backend. The local can be accessed still on [name]-local input name if it is ever needed.

The general idea behind /career is to in the future expand it to integrate with contactor.

### CODE REVIEW

**Comment by JohanHjelsethStorstad** [comment]
Oh and it also adds functionality to actually archive jobads hehe

**Comment by JohanHjelsethStorstad** [comment]
With this PR I belive the JobAd system is ready for release

**Review by theodorklauritzen — APPROVED** [review]
Topp! I hope contactor will be happy for this :))

**Review by Paulijuz — APPROVED** [review]
LGTM!

The only thing I think is a bit weird is that the "for bedrifter" page shows "bedrifter" as a page as if everyone is going to visit it. Shouldn't it really just be an admin page or just a smaller link/gear icon or something that just contacter can see? 

Unrelated, but new actions system is really nice. Just look how simple it is to create an action!

**Pull request merged**
